# 프라미스 API

`Promise`객체는 비동기 작업이 맞이할 미래의 완료 또는 실패와 그 결과 값을 나타낸다. 즉, 비동기 작업이 완료된 후 결과 값이나 에러 객체를 반환 해 사용할 수 있다.

`Promise`는 다음 중 하나의 상태를 가진다.

1. 대기(`pending`): 연산이 시작되지 않은, 초기 상태
2. 이행(`fulfilled`): 연산이 성공적으로 완료된 상태
3. 거부(`rejected`): 연산이 실패한 상태

이 3 가지의 상태를 사용해 `Promise`는 비동기 연산 후 그 이후의 연산에 결과 값이나 에러 객체를 제공할 수 있다. 그리고 이 `Promise`를 좀 더 유용하게 사용할 수 있도록 도와주는 6가지 정적 메서드가 있는데 오늘은 이 6가지의 정적 메서드에 대해 포스팅하려고 한다.

## Promise.all

`Promise.all`은 여러 개의 `Promise`를 이터러블한 객체로 받아 모든 `Promise`를 이행 한 후 해당 `Promise`들의 결과 값을 배열에 담아 반환한다.

```jsx
Promise.all([
  new Promise((res) => setTimeout(() => res(3), 1000)),
  new Promise((res) => setTimeout(() => res(1), 2000)),
  new Promise((res) => setTimeout(() => res(2), 3000)),
]).then(console.log);

// [ 3, 1, 2 ]
```

다음과 같이 `Promise`가 이행된 순서대로 반환 값을 배열에 담아 반환한다. 마지막 `Promise`가 종료되는 시점인 3초 후에 `Promise.all`이 종료된다.

```jsx
Promise.all([
  new Promise((res) => setTimeout(() => res(3), 1000)),
  new Promise((res, rej) => setTimeout(() => rej(1), 2000)),
  new Promise((res) => setTimeout(() => res(2), 3000)),
])
  .then(console.log)
  .catch(console.error);

// 1
```

하지만 거부된 `Promise`(`rejected`)가 있다면 `Promise.all`은 단락된다. 다음 코드에서는 2초 후에 `rej(1)`함수가 실행되므로 `console.error`메서드가 실행되 1이 출력된다.

즉, `Promise.all`은 모든 `Promise`가 이행될 경우 `Promise`들의 결과 값을 이행된 순서대로 배열에 담아 반환하지만 하나라도 거부된 `Promise`가 있다면 그 즉시 `Promise.all` 메서드는 종료되고 에러 핸들링 함수로 실패한 에러 객체가 전달된다.

하지만 `Promise.all`메서드가 거부된 `Promise`로 인해 종료되었다고 해도 인자로 받은 `Promise`들이 실행되지 않는 것은 아니다.

```jsx
Promise.all([
  new Promise((res) => setTimeout(() => res(3), 1000)),
  new Promise((res, rej) => setTimeout(() => rej(1), 2000)),
  new Promise((res) =>
    setTimeout(() => {
      console.log('run');
      res(2);
    }, 3000)
  ),
])
  .then(console.log)
  .catch(console.error);

// 1
// run
```

다음과 같이 `Promise.all`은 중간에 단락되어 에러 1을 출력하지만 인자로 들어간 세 번째 `Promise`는 중간에 단락된 `Promise.all`과는 상관없이 실행되는 것을 볼 수 있다.

## Promise.allSettled

`Promise.all`은 중간에 거부된 `Promise`가 있다면 단락되지만 `Promise.allSettled`는 모든 `Promise`가 처리될 때까지 기다린다. 중간에 거부된 `Promise`가 있더라도 말이다.

```jsx
Promise.allSettled([
  new Promise((res) => setTimeout(() => res(3), 1000)),
  new Promise((res, rej) => setTimeout(() => rej(1), 2000)),
  new Promise((res) => setTimeout(() => res(2), 3000)),
])
  .then(console.log)
  .catch(console.error);

/* [
  { status: 'fulfilled', value: 3 },
  { status: 'rejected', reason: 1 },
  { status: 'fulfilled', value: 2 }
] */
```

그럼 아까 작성한 `Promise`를 메서드만 `Promise.allSettled`로 바꾸어 실행해 보았더니 다음과 같이 `Promise`가 이행 또는 거부된 순서대로 `Promise`의 상태와 값을 배열로 반환해주는 것을 볼 수 있다.

다음과 같이 `Promise.allSettled`는 인자로 이터러블한 `Promise`들을 인자로 받으며, `Promise`의 이행, 거부 결과에 상관 없이 인자로 넣어준 모든 `Promise`의 상태와 값 또는 에러를 전달 받을 수 있다.

다만 `Promise.allSettled`는 ES2020에 새로 추가된 스펙이기 때문에 지원하지 않는 환경이라면 폴리필을 추가로 구현해줘야 한다.

## Promise.race

`Promise.race`는 `Promise.all`과 비슷하다. 인자 역시 이터러블한 `Promise`들을 받는다. 하지만 가장 먼저 처리되는 `Promise`의 결과를 반환해 주는데, `Promise`가 이행되거나 거부되는것과 상관 없이 결과를 반환한다.

```jsx
Promise.race([
  new Promise((res, rej) => setTimeout(() => rej(1), 1000)),
  new Promise((res) => setTimeout(() => res(3), 2000)),
  new Promise((res) => setTimeout(() => res(2), 3000)),
])
  .then(console.log)
  .catch(console.error);

// 1
```

다음과 같이 `Promise.race`를 구현해 봤다. 가장 먼저 1초 후에 `rej(1)`함수가 실행되므로 `Promise`가 `catch`로 에러를 보내주고 `Promise.race`는 그 즉시 종료되며 다른 `Promise`들의 결과 또는 에러는 무시된다.

하지만 결과 또는 에러가 무시된다는 말이 다른 `Promise`들이 실행되지 않는다는 의미는 아니며 빈 배열이 인자로 들어오면 `Promise.race`는 영원히 대기(`pending`)상태인 `Promise`를 반환한다.

## Promise.any

`Promise.any`역시 이터러블한 `Promise`들을 인자로 받는다. 그리고 `Promise.race`와 아주 유사하게 동작한다. 하지만 다른점은 `Promise.any`는 가장 먼저 이행된 `Promise`를 반환하며 단락된다.

```jsx
Promise.any([
  new Promise((res, rej) => setTimeout(() => rej(1), 1000)),
  new Promise((res) => setTimeout(() => res(3), 2000)),
  new Promise((res) => setTimeout(() => res(2), 3000)),
]).then(console.log);

// 3
```

다음 코드를 보면 `rej(1)`로 첫 번째 `Promise`가 가장 먼저 처리되었지만, 가장 먼저 이행된 두 번째 `Promise`를 반환하는 것을 볼 수 있다.

즉, `Promise.any`는 받은 `Promise` 중 하나라도 성공하면 에러가 발생하지 않고 첫 번째로 성공한 `Promise`의 결과 값을 반환하지만 입력된 `Promise`들이 모두 실패하면 에러를 반환한다. 빈 배열이 인자로 들어오는 경우에도 마찬가지로 성공한 `Promise`가 없다고 판단해 에러를 반환한다.

## Promise.reslove/reject

사실 ES2017 이후 `async/await` 문법이 추가된 이후 사용하는 경우가 많이 줄었지만 그래도 어떤 개념인지 알아둬서 나쁠건 없기 때문에 포스팅에 추가하였다.

### Promise.resolve

```jsx
console.log(Promise.resolve(1));
// Promise {<fulfilled>: 1}
```

`Promise.resolve`는 이행(`fulfilled`)상태와 인자로 넣어준 결과값을 가진 `Promise` 객체를 생성한다. 호환성을 위해 함수가 `Promise`를 반환하도록 해야 할 때 사용할 수 있다.

### Promise.reject

```jsx
console.log(Promise.reject(1));
```

반대로 `Promise.reject`는 거부(`rejected`)상태와 인자로 넣어준 에러값을 가진 `Promise` 객체를 생성한다.

## 결론

`Promise`클래스는 총 6개의 정적 메서드(ES2021 기준)을 가지고 있는데 실제로 `Promise.all`을 가장 많이 사용해본다고 하고, 나도 직접 사용해본 메서드는 `Promise.all`정도만 있는 것 같다. 사실 `async/await` 문법이 추가되면서 `Promise`를 직접 다룰 일 자체가 많이 사라진 것 같은데 그래도 종종 사용할 일이 있어서 이번에 `Promise`의 메서드를 정리하는게 많은 도움이 된 것 같다.